/**
 * Codes d'erreur standardisés pour l'application
 */

module.exports = {
  // Erreurs d'authentification
  AUTH_INVALID_CREDENTIALS: 'AUTH001',
  AUTH_TOKEN_EXPIRED: 'AUTH002',
  AUTH_TOKEN_INVALID: 'AUTH003',
  AUTH_UNAUTHORIZED: 'AUTH004',
  AUTH_FORBIDDEN: 'AUTH005',
  AUTH_USER_NOT_FOUND: 'AUTH006',
  AUTH_USER_DISABLED: 'AUTH007',
  AUTH_OAUTH_FAILED: 'AUTH008',
  
  // Erreurs de base de données
  DB_CONNECTION_ERROR: 'DB001',
  DB_QUERY_ERROR: 'DB002',
  DB_CONSTRAINT_VIOLATION: 'DB003',
  DB_DUPLICATE_ENTRY: 'DB004',
  DB_TRANSACTION_FAILED: 'DB005',
  DB_NOT_FOUND: 'DB006',
  
  // Erreurs métier
  BUSINESS_INVALID_OPERATION: 'BUS001',
  BUSINESS_LIMIT_EXCEEDED: 'BUS002',
  BUSINESS_INSUFFICIENT_PERMISSIONS: 'BUS003',
  BUSINESS_RESOURCE_LOCKED: 'BUS004',
  BUSINESS_INVALID_STATE: 'BUS005',
  BUSINESS_QUOTA_EXCEEDED: 'BUS006',
  
  // Erreurs de validation
  VALIDATION_REQUIRED_FIELD: 'VAL001',
  VALIDATION_INVALID_FORMAT: 'VAL002',
  VALIDATION_INVALID_LENGTH: 'VAL003',
  VALIDATION_INVALID_TYPE: 'VAL004',
  VALIDATION_INVALID_ENUM: 'VAL005',
  VALIDATION_CUSTOM_RULE: 'VAL006',
  
  // Erreurs de paiement
  PAYMENT_CARD_DECLINED: 'PAY001',
  PAYMENT_INSUFFICIENT_FUNDS: 'PAY002',
  PAYMENT_INVALID_CARD: 'PAY003',
  PAYMENT_PROCESSING_ERROR: 'PAY004',
  PAYMENT_REFUND_FAILED: 'PAY005',
  
  // Erreurs de communication
  COMM_EMAIL_SEND_FAILED: 'COM001',
  COMM_SMS_SEND_FAILED: 'COM002',
  COMM_NOTIFICATION_FAILED: 'COM003',
  COMM_WEBHOOK_FAILED: 'COM004',
  
  // Erreurs système
  SYSTEM_INTERNAL_ERROR: 'SYS001',
  SYSTEM_SERVICE_UNAVAILABLE: 'SYS002',
  SYSTEM_RATE_LIMIT_EXCEEDED: 'SYS003',
  SYSTEM_MAINTENANCE_MODE: 'SYS004',
  SYSTEM_FILE_NOT_FOUND: 'SYS005',
  SYSTEM_CONFIGURATION_ERROR: 'SYS006',
  
  // Erreurs WebSocket
  WS_CONNECTION_FAILED: 'WS001',
  WS_AUTHENTICATION_FAILED: 'WS002',
  WS_INVALID_MESSAGE: 'WS003',
  WS_ROOM_NOT_FOUND: 'WS004',
  
  // Erreurs de cache
  CACHE_CONNECTION_FAILED: 'CACHE001',
  CACHE_KEY_NOT_FOUND: 'CACHE002',
  CACHE_OPERATION_FAILED: 'CACHE003'
}